export enum TodosActionTypes {
    ADD_TODO = 'ADD_TODO',
    UPDATE_TODO_EDITING = 'UPDATE_TODO_EDITING',
    ADD_TODO_BASKET = 'ADD_TODO_BASKET',
    UPDATE_VALUE_EDITING_TODO = 'CHANGE_VALUE_EDITING_TODO',
    UPDATE_TODO_CHECKBOX = 'UPDATE_TODO_CHECKBOX',
    REMOVE_TODO_BASKET = 'REMOVE_TODO_BASKET',
    CANCEL_TODO_BASKET = 'CANCEL_TODO_BASKET',
    CANCEL_TODO_EDITING = 'CANCEL_TODO_EDITING'
}